//
// Created by gabriele on 30/01/21.
//

#ifndef FOUR_IN_A_ROW_HEADERS_H
#define FOUR_IN_A_ROW_HEADERS_H

//AUTHENTICATION HEADERS
#define HELLORQST 38
#define HELLORESP 39
#define HELLOACCEPT 40
#define HELLOREFUSE 42
#define PORTINFO 41

//CHALLENGE REQUEST HEADERS
#define USERLISTRQST 45
#define USERLISTRESP 46
#define CHLRQST 56
#define CHLRESP 57

#define BUSYPEER 58
#define NOTLOGGEDPEER 59

#define ACCEPT 98
#define REFUSE 99

#define CHLINFO 100

//PEERS AUTHENTICATION
#define KEYEXCHRQST 134
#define KEYEXCHRESP 135
#define KEYEXCHCONFIRM 136

#define FREESTATE 150

//GAME HEADERS

#define GAMEMOVE 145
#define GAMECLOSE 146
#endif //FOUR_IN_A_ROW_HEADERS_H
